name        : gnome-session
version     : 3.18.1
release     : 7
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-session/3.18/gnome-session-3.18.1.tar.xz : 84b82432fd51a115a267a929ca293d88de0ed4ba681d6be44849fd47a4efa191
license     :
    - GPLv2+
summary     : Provides GNOME session core
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(sm)
    - pkgconfig(gl)
    - pkgconfig(xtst)
    - pkgconfig(xtrans)
description : |
    Provides GNOME session core
setup      : |
    %configure --enable-systemd
build      : |
    %make
install    : |
    %make_install
