name        : gnome-session
version     : 3.18.1.2
release     : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-session/3.18/gnome-session-3.18.1.2.tar.xz : b37d823d57ff2e3057401a426279954699cfe1e44e59a4cbdd941687ff928a45
license     :
    - GPLv2+
summary     : Provides GNOME session core
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(sm)
    - pkgconfig(gl)
    - pkgconfig(xtst)
    - pkgconfig(xtrans)
description : |
    Provides GNOME session core
setup      : |
    %configure --enable-systemd
build      : |
    %make
install    : |
    %make_install
