name       : gnome-session
version    : 3.20.2
release    : 10
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-session/3.20/gnome-session-3.20.2.tar.xz : 025f97e0b9f5431890598d6130040e1e7071771cc29e1d29d8e2e7c84d95f6da
license    :
    - GPL-2.0
summary    : Provides GNOME session core
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(sm)
    - pkgconfig(gl)
    - pkgconfig(xtst)
    - pkgconfig(xtrans)
patterns   :
    - shell:
        - /usr/share/xsessions
        - /usr/share/wayland-sessions
summaries  :
    - shell: Runtime support for GNOME Shell Session
description: |
    Provides GNOME session core
setup      : |
    %configure --enable-systemd
build      : |
    %make
install    : |
    %make_install
