name       : gnome-session
version    : 3.26.1
release    : 18
source     :
    - https://download.gnome.org/sources/gnome-session/3.26/gnome-session-3.26.1.tar.xz : d9414b368db982d3837ca106e64019f18e6cdd5b13965bea6c7d02ddf5103708
license    : GPL-2.0
summary    : Provides GNOME session core
summaries  :
    - shell : Runtime support for GNOME Shell Session
description: |
    Provides GNOME session core
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xtrans)
    - pkgconfig(xtst)
patterns   :
    - shell :
        - /usr/share/xsessions
        - /usr/share/wayland-sessions
setup      : |
    %configure --enable-systemd
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/xsessions/gnome-xorg.desktop $installdir/usr/share/xsessions/gnome.desktop
