name       : gnome-session
version    : 3.22.3
release    : 13
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-session/3.22/gnome-session-3.22.3.tar.xz : cc486fc84d892fa744a382b5ea8b9b40fc5045bc0d5feccfb02e80137eab77e5
license    :
    - GPL-2.0
summary    : Provides GNOME session core
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(sm)
    - pkgconfig(gl)
    - pkgconfig(xtst)
    - pkgconfig(xtrans)
patterns   :
    - shell :
        - /usr/share/xsessions
        - /usr/share/wayland-sessions
summaries  :
    - shell : Runtime support for GNOME Shell Session
description: |
    Provides GNOME session core
setup      : |
    %configure --enable-systemd
build      : |
    %make
install    : |
    %make_install
