name       : gnome-session
version    : '44.0'
release    : 38
source     :
    - https://download.gnome.org/sources/gnome-session/44/gnome-session-44.0.tar.xz : ccf829a96526135e9e9f917526515d36a5092bdfa316f3737dd8c5a524dbf2c6
license    : GPL-2.0-or-later
summary    :
    - Provides GNOME session core
    - shell : Runtime support for GNOME Shell Session
    - shell-experimental : Experimental Wayland Session for GNOME Shell
description:
    - Provides GNOME session core
    - shell : Runtime support for GNOME Shell Session
    - shell-experimental : Experimental Wayland Session for GNOME Shell
component  :
    - desktop.gnome.core
    - shell : desktop.gnome
    - shell-experimental : desktop.gnome
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xtrans)
    - pkgconfig(xtst)
    - docbook-xml
    - xmlto
rundeps    :
    - gsettings-desktop-schemas
    - gvfs
    - udisks
    - upower
    - xdg-user-dirs
    - xdg-user-dirs-gtk
    - xdg-utils
    - shell :
        - gnome-session
patterns   :
    - shell :
        - /usr/share/xsessions
        - /usr/share/wayland-sessions
replaces   :
    - shell :
        - gnome-session-shell-experimental
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-grep-error-for-etc-shells-on-Solus.patch
    %meson_configure -Dsystemd=true \
                     -Dsystemd_journal=true \
                     -Dsystemd_session="default"
build      : |
    %ninja_build
install    : |
    %ninja_install
