name       : gnome-session
version    : 3.22.2
release    : 11
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-session/3.22/gnome-session-3.22.2.tar.xz : 361a31edb4f8c6d410f1029eee089422e25a2da6c287ead40fccdea5bda450f5
license    :
    - GPL-2.0
summary    : Provides GNOME session core
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(sm)
    - pkgconfig(gl)
    - pkgconfig(xtst)
    - pkgconfig(xtrans)
patterns   :
    - shell :
        - /usr/share/xsessions
        - /usr/share/wayland-sessions
summaries  :
    - shell : Runtime support for GNOME Shell Session
description: |
    Provides GNOME session core
setup      : |
    %configure --enable-systemd
build      : |
    %make
install    : |
    %make_install
